import type { Metadata } from "next";
import { Exo } from "next/font/google";
import { getServerSession } from "next-auth";
import { nextAuthConfig } from "@/NextAuth/NextAuth";
import "./globals.css";
import { Toaster } from "sonner";
import MySession from "./_Components/MySession/MySession";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import ReduxProvider from "@/store/ReduxProvider";
import AppShell from "./_Components/AppShell";

const exoFont = Exo({
  subsets: ["latin"],
  variable: "--font-exo",
});

export const metadata: Metadata = {
  title: "Fresh cart",
  description: "Generated by ziad sayed",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(nextAuthConfig);

  return (
    <html lang="en" className={exoFont.variable} suppressHydrationWarning>
      <body className={`font-exo antialiased`} suppressHydrationWarning>
        <MySession session={session}>
          <ReduxProvider>
            <AppShell>
              {children}
            </AppShell>
            <Toaster />
            <ToastContainer position="top-right" autoClose={3000} />
          </ReduxProvider>
        </MySession>
      </body>
    </html>
  );
}
